name: Deploy to Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.3'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Start SSH Agent and Add Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Add SSH known hosts
      run: ssh-keyscan -H jorendhaen.be >> /home/runner/.ssh/known_hosts
      shell: bash

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no jorendha@jorendhaen.be 'echo "SSH connection successful"'
      shell: bash

    - name: Deploy to server
      run: |
        rsync -rltgoDzvO --delete -e "ssh -o StrictHostKeyChecking=no" dist/ jorendha@jorendhaen.be:/home/jorendha/public_html/portfolio
      shell: bash

