name: Deploy to Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.3'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/deploy_key
        chmod 600 /home/runner/.ssh/deploy_key
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add /home/runner/.ssh/deploy_key
      shell: bash

    - name: Add SSH known hosts
      run: ssh-keyscan -H jorendhaen.be >> /home/runner/.ssh/known_hosts
      shell: bash

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no jorendha@jorendhaen.be 'echo "SSH connection successful"'
      shell: bash

    - name: Deploy to server
      run: |
        rsync -rltgoDzvO --delete -e "ssh -o StrictHostKeyChecking=no" dist/ jorendha@jorendhaen.be:/home/jorendha/public_html/portfolio
      shell: bash

