name: Deploy to Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Setup Node.js
#      uses: actions/setup-node@v3
#      with:
#        node-version: '21.7.3'
#
#    - name: Install dependencies
#      run: npm install
#
#    - name: Build the project
#      run: npm run build
#
#    - name: Set up SSH key
#      run: |
#        env
#        mkdir -p ~/.ssh
#        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#        ssh-keyscan -p 22 jorendhaen.be >> ~/.ssh/known_hosts
#        sudo apt-get install sshpass


    - name: Debug - Show passphrase
      run: |
        printf "Passphrase: %s\n" "${{ secrets.SSH_PASSPHRASE }}"

#    - name: Upload dist folder to server
#      env:
#        SSHPASS: ${{ secrets.SSH_PASSPHRASE }}
#      run: |
#        sshpass -e rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ jorendha@jorendhaen.be:/home/jorendha/public_html/portfolio
#
#
#    - name: Upload dist folder to server
#      run: |
#        rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ jorendha@jorendhaen.be:/home/jorendha/public_html/portfolio
#
#
#    - name: Upload dist folder to server
#      run: |
#        sshpass -p '${{ secrets.SSH_PASSPHRASE }}' rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ jorendha@jorendhaen.be:/home/jorendha/public_html/portfolio
#
#    - name: Deploy to server
#      run: |
#        sshpass -p '${{ secrets.SSH_PASSPHRASE }}' ssh -v -o StrictHostKeyChecking=no jorendha@jorendhaen.be <<'ENDSSH'
#        ENDSSH


